#define yy_create_buffer atc_create_buffer
#define yy_delete_buffer atc_delete_buffer
#define yy_scan_buffer atc_scan_buffer
#define yy_scan_string atc_scan_string
#define yy_scan_bytes atc_scan_bytes
#define yy_flex_debug atc_flex_debug
#define yy_init_buffer atc_init_buffer
#define yy_flush_buffer atc_flush_buffer
#define yy_load_buffer_state atc_load_buffer_state
#define yy_switch_to_buffer atc_switch_to_buffer
#define yyin atcin
#define yyleng atcleng
#define yylex atclex
#define yyout atcout
#define yyrestart atcrestart
#define yytext atctext
#define yywrap atcwrap

#line 20 "atomizer_c.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
static yyconst short int yy_accept[244] =
    {   0,
        0,    0,   74,   72,    2,    1,    7,   72,    5,    3,
        3,   72,    3,    7,    3,    3,    7,    3,   65,   65,
        7,    7,    3,    7,   62,   62,    7,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,    3,    2,   22,    0,   70,    0,   13,   25,
       15,    0,   68,    0,   11,   27,    9,   28,   10,   29,
        0,   66,    4,    6,   12,   66,   64,   65,    0,   65,
       65,    0,   17,   23,   21,   24,   18,   62,    0,    0,
       14,   62,   62,   62,   62,   62,   62,   37,   62,   62,
       62,   62,   62,   62,   45,   62,   62,   62,   62,   62,

       62,   62,   62,   62,   62,   62,   16,   26,    0,   70,
        0,    0,   68,    0,    8,    0,   66,   64,   64,    0,
       67,   63,   19,   20,    0,   71,    0,    0,   69,    0,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   43,   62,   46,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,    0,
       66,   67,   63,   63,    0,   71,    0,    0,   69,    0,
       30,   62,   32,   33,   62,   62,   62,   62,   39,   40,
       62,   62,   44,   47,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   59,   62,   62,   31,   34,

       62,   62,   62,   62,   42,   62,   62,   50,   62,   62,
       62,   62,   62,   62,   57,   62,   62,   61,   62,   62,
       38,   41,   62,   49,   51,   52,   53,   54,   55,   62,
       62,   62,   62,   36,   62,   56,   62,   62,   35,   48,
       58,   60,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       10,   11,   12,   10,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   18,   18,   19,   10,   20,
       21,   22,   10,    1,   23,   23,   23,   23,   24,   25,
       26,   26,   26,   26,   26,   27,   26,   26,   26,   26,
       26,   26,   26,   26,   28,   26,   26,   29,   26,   26,
       19,   30,   19,   31,   26,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   26,   41,   42,   43,   44,
       45,   46,   26,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   10,   56,   10,   10,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[57] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    2,    2,    1,    1,
        1,    1,    2,    2,    2,    3,    3,    3,    3,    1,
        1,    2,    2,    2,    2,    2,    2,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1
    } ;

static yyconst short int yy_base[254] =
    {   0,
        0,    0,  380,  381,  377,  381,  357,   52,  381,  356,
       50,   50,  381,  355,   48,   51,   49,   63,   71,   74,
      381,   41,  354,   54,    0,   72,  353,  323,  325,   47,
       57,   52,   59,  326,   71,  325,  333,   70,  314,  323,
      321,  326,   62,  362,  381,  101,  381,  109,  381,  381,
      381,  102,  381,  114,  381,  381,  381,  381,  381,  381,
      349,  112,  381,  381,  381,  117,  141,    0,  134,   98,
      118,    0,  341,  381,  381,  381,  340,    0,  133,  134,
      381,  311,  323,  310,  325,  312,  318,  304,  305,  302,
      302,  305,  302,  299,    0,  298,  302,  118,  300,  123,

      134,  304,  297,  122,   28,  302,  381,  381,  166,  167,
      170,  165,  171,  173,  381,  172,  381,  152,  160,  188,
      191,  171,  381,  381,  181,  381,  207,  184,  381,  214,
      296,  308,  303,  291,  170,  305,  303,  299,  291,  297,
      300,    0,  286,    0,  292,  289,  278,  280,  282,  289,
      275,  273,  273,  285,  275,  279,  283,  285,  274,  208,
      213,  381,  193,  200,  210,  217,  229,  224,  227,  236,
        0,  274,    0,    0,  265,  273,  262,  269,    0,    0,
      263,  260,    0,    0,  260,  260,  257,  269,  259,  263,
      268,  267,  265,  255,  260,    0,  248,  260,    0,    0,

      251,  252,  257,  221,    0,  215,  219,    0,  227,  224,
      226,  209,  217,  219,    0,  209,  212,    0,  201,  200,
        0,    0,  212,    0,    0,    0,    0,    0,    0,  209,
      207,  199,  156,    0,   79,    0,   85,   80,    0,    0,
        0,    0,  381,  266,  269,  271,  274,  277,   95,  280,
      283,  286,  289
    } ;

static yyconst short int yy_def[254] =
    {   0,
      243,    1,  243,  243,  243,  243,  243,  244,  243,  243,
      243,  245,  243,  243,  243,  243,  243,  243,  243,   19,
      243,  243,  243,  243,  246,  246,  243,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  243,  243,  243,  244,  243,  247,  243,  243,
      243,  245,  243,  248,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,   20,  243,  243,
      243,  249,  243,  243,  243,  243,  243,  246,  250,  251,
      243,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,

      246,  246,  246,  246,  246,  246,  243,  243,  244,  244,
      247,  245,  245,  248,  243,  243,  243,  243,  243,  243,
      243,  249,  243,  243,  250,  243,  252,  251,  243,  253,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  243,
      243,  243,  243,  243,  250,  250,  252,  251,  251,  253,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,

      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,    0,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243
    } ;

static yyconst short int yy_nxt[438] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   20,   21,   22,
       23,   24,   25,   25,   25,   25,   26,   25,   25,    4,
       27,   28,   29,   30,   31,   32,   33,   34,   25,   35,
       25,   36,   25,   25,   25,   25,   37,   38,   39,   40,
       41,   42,   25,   25,   25,   43,   47,   50,   53,   56,
       73,   74,   61,   58,   62,   62,   62,  157,   57,  158,
       51,   59,   60,   63,   76,   77,   79,   64,   84,   54,
       80,   48,  107,   65,   66,   85,   67,   67,   68,   68,
       68,   86,   87,   89,   69,   90,  122,   70,   71,   72,

       92,   88,  243,   93,   91,   47,   69,   95,   99,  100,
       53,   46,   70,  110,   96,  242,   52,  108,  101,  241,
       71,  102,  113,   72,   70,  240,  243,   62,   62,   62,
       48,   54,   62,   62,   62,  116,  117,  126,  111,   70,
      116,  117,  129,  114,   70,  120,  120,  116,  117,  121,
      121,  121,  116,  117,   66,  146,   67,   67,   68,   70,
      149,  155,  127,  130,   69,  151,  147,  118,  119,  156,
       47,   47,   46,   53,  110,   52,   69,  150,  118,   53,
      152,  113,  118,  160,  160,  126,  118,  161,  161,  161,
      119,  239,  129,  118,   54,   48,   48,  163,  164,  111,

       54,  118,  114,  121,  121,  121,  121,  121,  121,  125,
      127,  166,  163,  130,  126,  162,  128,  175,  176,  163,
      164,  126,  169,  161,  161,  161,  163,  162,  161,  161,
      161,  125,  129,  166,  163,  129,  167,  117,  128,  127,
      238,  163,  237,  170,  169,  236,  127,  235,  234,  117,
      233,  232,  231,  130,  230,  229,  130,  228,  167,  227,
      226,  225,  224,  223,  222,  170,   46,   46,   46,   52,
       52,   52,   78,   78,  109,  109,  109,  112,  112,  112,
      125,  125,  125,  128,  128,  128,  165,  165,  165,  168,
      168,  168,  221,  220,  219,  218,  217,  216,  215,  214,

      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  174,  173,  172,
      171,  159,  154,  153,  148,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  133,  132,  131,
      124,  123,  115,   44,  106,  105,  104,  103,   98,   97,
       94,   83,   82,   81,   75,   55,   49,   45,   44,  243,
        3,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,

      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243
    } ;

static yyconst short int yy_chk[438] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,   11,   12,   15,
       22,   22,   17,   16,   17,   17,   17,  105,   15,  105,
       11,   16,   16,   18,   24,   24,   26,   18,   30,   12,
       26,    8,   43,   18,   19,   30,   19,   19,   19,   20,
       20,   30,   31,   32,   19,   32,  249,   19,   19,   19,

       33,   31,   20,   33,   32,   46,   19,   35,   38,   38,
       52,   48,   19,   48,   35,  238,   54,   43,   38,  237,
       19,   38,   54,   19,   70,  235,   20,   62,   62,   62,
       46,   52,   66,   66,   66,   62,   62,   79,   48,   70,
       66,   66,   80,   54,   71,   69,   69,   62,   62,   69,
       69,   69,   66,   66,   67,   98,   67,   67,   67,   71,
      100,  104,   79,   80,   67,  101,   98,   67,   67,  104,
      109,  110,  111,  112,  111,  114,   67,  100,  118,  113,
      101,  114,   67,  116,  116,  125,  119,  116,  116,  116,
       67,  233,  128,  118,  112,  109,  110,  122,  122,  111,

      113,  119,  114,  120,  120,  120,  121,  121,  121,  127,
      125,  127,  122,  128,  165,  121,  130,  135,  135,  163,
      122,  166,  130,  160,  160,  160,  164,  121,  161,  161,
      161,  167,  168,  167,  163,  169,  127,  161,  170,  165,
      232,  164,  231,  130,  170,  230,  166,  223,  220,  161,
      219,  217,  216,  168,  214,  213,  169,  212,  167,  211,
      210,  209,  207,  206,  204,  170,  244,  244,  244,  245,
      245,  245,  246,  246,  247,  247,  247,  248,  248,  248,
      250,  250,  250,  251,  251,  251,  252,  252,  252,  253,
      253,  253,  203,  202,  201,  198,  197,  195,  194,  193,

      192,  191,  190,  189,  188,  187,  186,  185,  182,  181,
      178,  177,  176,  175,  172,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  145,
      143,  141,  140,  139,  138,  137,  136,  134,  133,  132,
      131,  106,  103,  102,   99,   97,   96,   94,   93,   92,
       91,   90,   89,   88,   87,   86,   85,   84,   83,   82,
       77,   73,   61,   44,   42,   41,   40,   39,   37,   36,
       34,   29,   28,   27,   23,   14,   10,    7,    5,    3,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,

      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "atomizer_c.l"
#define INITIAL 0
#line 2 "atomizer_c.l"

#include <stdio.h>
#include <string.h>

#include "main.h"
#include "atom.h"
#include "atom_codes.h"
#include "metrics.h"

/*
Macro for distinction by another parser
---
Makro rozpoznawane przez parser getatoms
*/
#define _ATOM(name) name

#define YY_DECL ATOM yylex()

static int lineno;
static int offset;
static int column;

static void skip_comment();
static ATOM construct_atom(int type);
static int handle_single_char(int c);
static int handle_token(int t);
static int decision;

struct metrics atcMetrics;
static UNIQUE_DICTIONARY atcId;

#define DECIDE(atom) { if((decision=handle_token(atom))!=-1) return construct_atom(decision); }

#line 595 "atomizer_c.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 44 "atomizer_c.l"


#line 749 "atomizer_c.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 244 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 381 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 46 "atomizer_c.l"
{ ++lineno; ++offset; column=0; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 47 "atomizer_c.l"
{ offset += yyleng; column += yyleng; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 48 "atomizer_c.l"
{
   decision = handle_single_char (*yytext);
   if (decision != -1)
     return construct_atom(decision);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 54 "atomizer_c.l"
{ skip_comment(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 55 "atomizer_c.l"
{ ++offset; do decision = input(), offset++; while (decision != '\n'); lineno++; column=0; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 56 "atomizer_c.l"
{ offset+=2; do decision = input(), offset++; while (decision != '\n'); lineno++; column=0; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "atomizer_c.l"
handle_single_char(*yytext);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "atomizer_c.l"
DECIDE(_ATOM(ELLIPSIS));
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "atomizer_c.l"
DECIDE(_ATOM(ADDEQ));
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "atomizer_c.l"
DECIDE(_ATOM(SUBEQ));
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "atomizer_c.l"
DECIDE(_ATOM(MULEQ));
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "atomizer_c.l"
DECIDE(_ATOM(DIVEQ));
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "atomizer_c.l"
DECIDE(_ATOM(MODEQ));
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "atomizer_c.l"
DECIDE(_ATOM(XOREQ));
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 67 "atomizer_c.l"
DECIDE(_ATOM(ANDEQ));
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 68 "atomizer_c.l"
DECIDE(_ATOM(OREQ));
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "atomizer_c.l"
DECIDE(_ATOM(SL));
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 70 "atomizer_c.l"
DECIDE(_ATOM(SR));
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 71 "atomizer_c.l"
DECIDE(_ATOM(SLEQ));
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 72 "atomizer_c.l"
DECIDE(_ATOM(SREQ));
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 73 "atomizer_c.l"
DECIDE(_ATOM(EQ));
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 74 "atomizer_c.l"
DECIDE(_ATOM(NOTEQ));
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 "atomizer_c.l"
DECIDE(_ATOM(LTEQ));
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 76 "atomizer_c.l"
DECIDE(_ATOM(GTEQ));
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "atomizer_c.l"
DECIDE(_ATOM(ANDAND));
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "atomizer_c.l"
DECIDE(_ATOM(OROR));
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "atomizer_c.l"
DECIDE(_ATOM(PLUSPLUS));
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 "atomizer_c.l"
DECIDE(_ATOM(MINUSMINUS));
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 81 "atomizer_c.l"
DECIDE(_ATOM(ARROW));
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "atomizer_c.l"
DECIDE(_ATOM(AUTO));
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "atomizer_c.l"
DECIDE(_ATOM(BREAK));
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "atomizer_c.l"
DECIDE(_ATOM(CASE));
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "atomizer_c.l"
DECIDE(_ATOM(CHAR));
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 87 "atomizer_c.l"
DECIDE(_ATOM(CONST));
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 88 "atomizer_c.l"
DECIDE(_ATOM(CONTINUE));
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "atomizer_c.l"
DECIDE(_ATOM(DEFAULT));
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 90 "atomizer_c.l"
DECIDE(_ATOM(DO));
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 91 "atomizer_c.l"
DECIDE(_ATOM(DOUBLE));
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 92 "atomizer_c.l"
{ atcMetrics.else_keywords++; DECIDE(_ATOM(ELSE)); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 93 "atomizer_c.l"
DECIDE(_ATOM(ENUM));
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 94 "atomizer_c.l"
DECIDE(_ATOM(EXTERN));
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 95 "atomizer_c.l"
DECIDE(_ATOM(FLOAT));
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 96 "atomizer_c.l"
{ atcMetrics.for_keywords++; DECIDE(_ATOM(FOR)); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 97 "atomizer_c.l"
DECIDE(_ATOM(GOTO));
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 98 "atomizer_c.l"
{ atcMetrics.if_keywords++; DECIDE(_ATOM(IF)); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 99 "atomizer_c.l"
DECIDE(_ATOM(INT));
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 100 "atomizer_c.l"
DECIDE(_ATOM(LONG));
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 101 "atomizer_c.l"
DECIDE(_ATOM(REGISTER));
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 102 "atomizer_c.l"
DECIDE(_ATOM(RETURN));
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "atomizer_c.l"
DECIDE(_ATOM(SHORT));
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 104 "atomizer_c.l"
DECIDE(_ATOM(SIGNED));
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 105 "atomizer_c.l"
DECIDE(_ATOM(SIZEOF));
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 106 "atomizer_c.l"
DECIDE(_ATOM(STATIC));
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 107 "atomizer_c.l"
DECIDE(_ATOM(STRUCT));
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 108 "atomizer_c.l"
DECIDE(_ATOM(SWITCH));
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 109 "atomizer_c.l"
DECIDE(_ATOM(TYPEDEF));
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 110 "atomizer_c.l"
DECIDE(_ATOM(UNION));
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 111 "atomizer_c.l"
DECIDE(_ATOM(UNSIGNED));
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 112 "atomizer_c.l"
DECIDE(_ATOM(VOID));
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 113 "atomizer_c.l"
DECIDE(_ATOM(VOLATILE));
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 114 "atomizer_c.l"
{ atcMetrics.while_keywords++;  DECIDE(_ATOM(WHILE)); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 116 "atomizer_c.l"
{ atcMetrics.identifiers++; unique_dictionary_add(atcId, yytext); DECIDE(_ATOM(IDENTIFIER)); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 118 "atomizer_c.l"
DECIDE(_ATOM(INTEGER));
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 119 "atomizer_c.l"
DECIDE(_ATOM(INTEGER));
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 120 "atomizer_c.l"
DECIDE(_ATOM(INTEGER));
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 122 "atomizer_c.l"
DECIDE(_ATOM(FLOATING));
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 123 "atomizer_c.l"
DECIDE(_ATOM(FLOATING));
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 125 "atomizer_c.l"
DECIDE(_ATOM(CHARACTER));
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 126 "atomizer_c.l"
DECIDE(_ATOM(CHARACTER));
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 128 "atomizer_c.l"
DECIDE(_ATOM(STRING));
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 129 "atomizer_c.l"
DECIDE(_ATOM(STRING));
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 131 "atomizer_c.l"
{
  atcMetrics.lines=lineno;
  atcMetrics.unique_ids = atcId->count;
  free_unique_dictionary(atcId);
  free(atcId);
  return (ATOM)0;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 139 "atomizer_c.l"
{ fprintf(stderr, _("%d: unexpected character `%c'\n"), lineno, yytext[0]); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 141 "atomizer_c.l"
ECHO;
	YY_BREAK
#line 1211 "atomizer_c.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 244 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 244 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 243);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 141 "atomizer_c.l"


int
yywrap()
{
	return 1;
}

/*
 * Skip the comment - manually without matching
 * ---
 * Pominiêcie komentarza bez stosowania DAS
 */
static void
skip_comment()
{
	int c1, c2;

	offset += 2;  // for the /*
	column += 2;  // znaki /*

	c1 = input();
	c2 = input();

	while (c2 != EOF && !(c1 == '*' && c2 == '/'))
	{
		if (c1 == '\n')
		{
			++lineno;
			column = 0;
		}
		else
		    ++column;
		++offset;
		c1 = c2;
		c2 = input();
	}
	++column;
	++offset;
}

/*
Filter single-character tokens and return them as symbolic names
---
Filtrowanie tokenów, które s± jednoznakowe i zwracanie ich jako kodów symbolicznych
*/
int handle_single_char(int c)
{
  offset ++;
  column ++;
  switch(c)
  {
    /*
	Atoms which are not interesting
	---
	Atomy, które nie s± ciekawe
	*/
	case ';':
	  atcMetrics.semicolons++;
	case ',':
	  return -1;
	/*
	Interesting atoms
	---
	Atomy, które s± ciekawe
	*/
	case '[':
	case ']':
	case '(':
	case ')':
	  return _ATOM(BRACKET);
	case '.':
	  return _ATOM(SELECTOR);
	case '{':
	  return _ATOM(BEGN);
	case '}':
	  return _ATOM(END);
	case '+':
	  atcMetrics.plus++;
	  return _ATOM(ARITHMETIC);
	case '-':
	  atcMetrics.minus++;
	  return _ATOM(ARITHMETIC);
	case '*':
	  atcMetrics.times++;
	case '/':
	case '%':
	  return _ATOM(ARITHMETIC);
	case '^':
	case '&':
	case '|':
	case '~':
	  return _ATOM(BITWISE);
	case '!':
	case '?':
	case ':':
	  return _ATOM(LOGIC);
	case '<':
	case '>':
	  return _ATOM(RELATION);
	case '=':
	  atcMetrics.assignments++;
	  return _ATOM(ASSIGNMENT);
	/*
	Atoms we don't really know or distinct
	---
	Atomy, których nie znamy lub generalizujemy
	*/
	default:
	  return _ATOM(OTHER);
  }
  return _ATOM(IMPOSSIBLE);
}

int handle_token(int t)
{
  offset += yyleng;
  column += yyleng;
  switch(t)
  {
    case ADDEQ:  /* "+=" */
	  atcMetrics.plus++;
	  atcMetrics.assignments++;
	  return _ATOM(ASSIGNMENT);
    case SUBEQ:  /* "-=" */
	  atcMetrics.minus++;
	  atcMetrics.assignments++;
	  return _ATOM(ASSIGNMENT);
    case MULEQ:  /* "*=" */
	  atcMetrics.assignments++;
	  atcMetrics.times++;
	  return _ATOM(ASSIGNMENT);
    case DIVEQ:  /* "/=" */
    case MODEQ:  /* "%=" */
    case XOREQ:  /* "^=" */
    case ANDEQ:  /* "&=" */
    case OREQ:   /* "|=" */
	  atcMetrics.assignments++;
	  return _ATOM(ASSIGNMENT);
    case SL:     /* "<<" */
    case SR:     /* ">>" */
    case SLEQ:   /* "<<=" */
    case SREQ:   /* ">>=" */
	  return _ATOM(BITWISE);
    case ANDAND: /* "&&" */
    case OROR:   /* "||" */
	  return _ATOM(LOGIC);
    case PLUSPLUS:   /* "++" */
    case MINUSMINUS: /* "--" */
    case SIZEOF:     /* "sizeof" */
	  return _ATOM(ARITHMETIC);
    case ARROW:      /* "->" */
	  return _ATOM(SELECTOR);

    case FOR:       /* "for" */
    case CONTINUE:  /* "continue" */
    case GOTO:      /* "goto" */
    case IF:        /* "if" */
    case ELSE:      /* "else" */
    case WHILE:     /* "while" */
    case DO:        /* "do" */
    case SWITCH:    /* "switch" */
    case CASE:      /* "case" */
    case BREAK:     /* "break" */
    case DEFAULT:   /* "default" */
    case RETURN:    /* "return" */
	  return _ATOM(CONTROL);

    case CHAR:    /* "char" */
    case FLOAT:   /* "float" */
    case DOUBLE:  /* "double" */
    case INT:     /* "int" */
    case LONG:    /* "long" */
	  return _ATOM(BUILTINTYPE);
    case TYPEDEF: /* "typedef" */
    case UNION:   /* "union" */
    case ENUM:    /* "enum" */
    case STRUCT:  /* "struct" */
	  return _ATOM(DECL);

    case EQ:     /* "==" */
    case NOTEQ:  /* "!=" */
    case LTEQ:   /* "<=" */
    case GTEQ:   /* ">=" */
	  return _ATOM(RELATION);
	/*
	Tokens to be filtered out
	---
	Tokeny do odfiltrowania
	*/
    case SHORT:     /* "short" */
    case SIGNED:    /* "signed" */
    case STATIC:    /* "static" */
    case UNSIGNED:  /* "unsigned" */
    case ELLIPSIS:  /* "..." */
    case AUTO:      /* "auto" */
    case EXTERN:    /* "extern" */
    case VOLATILE:  /* "volatile" */
    case REGISTER:  /* "register" */
    case VOID:      /* "void" */
    case CONST:     /* "const" */
	  return -1;
	default:
	  return t;
  }
  return _ATOM(IMPOSSIBLE);
}

ATOM
construct_atom(int type)
{
  ATOM ret_atom;
  ret_atom = calloc(1, sizeof(struct atom));
  ret_atom->content = strdup(yytext);
  /*
  offset already updated by handle_token
  ---
  offset zosta³ ju¿ zmodyfikowany w funkcji handle_token
  */
  ret_atom->start   = offset - yyleng;
  ret_atom->len     = yyleng;
  ret_atom->code    = type;
  ret_atom->line    = lineno;
  return ret_atom;
}

void init_atclex()
{
  offset = 0;
  lineno = 1;
  column = 0;
  atcId = new_unique_dictionary();
}

