SELECT 'drop schema [' + SCHEMA_NAME + '];'
FROM INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME NOT IN
      (
          SELECT DISTINCT TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES
      )
      AND SCHEMA_NAME NOT IN ('sys', 'dbo', 'INFORMATION_SCHEMA', 'tmp', 'Debug', 'guest')
      AND SCHEMA_NAME NOT LIKE 'db_%';
