# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generator.ui'
#
# Created: Sun Dec 19 17:07:55 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(599, 285)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 30, 51, 21))
        self.label.setObjectName("label")
        self.temat = QtGui.QLineEdit(Dialog)
        self.temat.setGeometry(QtCore.QRect(340, 30, 133, 20))
        self.temat.setObjectName("temat")
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 51, 42))
        self.label_4.setObjectName("label_4")
        self.radioButton = QtGui.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(500, 20, 71, 18))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtGui.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(500, 40, 71, 18))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 61, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(170, 60, 71, 20))
        self.label_3.setObjectName("label_3")
        self.spozn = QtGui.QSpinBox(Dialog)
        self.spozn.setGeometry(QtCore.QRect(260, 60, 56, 20))
        self.spozn.setMaximum(10)
        self.spozn.setObjectName("spozn")
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(360, 60, 56, 20))
        self.label_6.setObjectName("label_6")
        self.punkty = QtGui.QSpinBox(Dialog)
        self.punkty.setGeometry(QtCore.QRect(420, 60, 57, 20))
        self.punkty.setMaximum(10)
        self.punkty.setProperty("value", 10)
        self.punkty.setObjectName("punkty")
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 56, 16))
        self.label_5.setObjectName("label_5")
        self.ocena = QtGui.QPlainTextEdit(Dialog)
        self.ocena.setGeometry(QtCore.QRect(9, 112, 569, 131))
        self.ocena.setObjectName("ocena")
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(9, 249, 444, 25))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.student = QtGui.QLineEdit(Dialog)
        self.student.setGeometry(QtCore.QRect(80, 30, 181, 20))
        self.student.setObjectName("student")
        self.raport = QtGui.QSpinBox(Dialog)
        self.raport.setGeometry(QtCore.QRect(80, 60, 64, 20))
        self.raport.setMinimum(1)
        self.raport.setMaximum(6)
        self.raport.setObjectName("raport")
        self.label.setBuddy(self.temat)
        self.label_4.setBuddy(self.student)
        self.label_2.setBuddy(self.raport)
        self.label_3.setBuddy(self.spozn)
        self.label_6.setBuddy(self.punkty)
        self.label_5.setBuddy(self.ocena)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.buttonBox, self.student)
        Dialog.setTabOrder(self.student, self.temat)
        Dialog.setTabOrder(self.temat, self.raport)
        Dialog.setTabOrder(self.raport, self.spozn)
        Dialog.setTabOrder(self.spozn, self.ocena)
        Dialog.setTabOrder(self.ocena, self.punkty)
        Dialog.setTabOrder(self.punkty, self.radioButton_2)
        Dialog.setTabOrder(self.radioButton_2, self.radioButton)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Temat:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Student:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("Dialog", "JwUM", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("Dialog", "JaPitI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Raport", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Spóźnienie:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Punkty", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Opis:", None, QtGui.QApplication.UnicodeUTF8))

